- redis/reply.go
- redis/reply_test.go
Hi, 
I suggest adding a helper function "Ints" to facilitate converting a the response interface to []int.
Example: 
c, err := dial()
if err != nil {
panic(err)
}
defer c.Close()
c.Do("SADD", "set_with_integers", 4, 5, 6)
ints, _ := redis.Ints(c.Do("SMEMBERS", "set_with_integers"))
fmt.Printf("%#v\n", ints)
// Output:
// []int{4, 5, 6}
> Add Ints reply helper function

- redis/reply.go
A helper function to map HGETALL response to a map[string]sting type.
> Scan HGETALL response to map

- redis/pool_test.go
The return parameter names 'reply' and 'err' are unused.
> Removed unused return parameter names

- redis/reply.go
Like in the description. 
Discovered it when i stopped redis server, but my app was returning errNil and not connection errors
> Fix bux causing Ints call to swallow error returned from the connecton object

- redis/conn.go
- redis/conn_test.go
After thinking about it some more, I think it's cleaner to take a URL
object instead of an unparsed string, but I think either way would work.
> Add DialURL to allow connection using a Redis URL

- redis/conn.go
The redis URL support added on 08/30 has a regex which only allows single digit database numbers.  This change allows for multi-digit database numbers.
> allow for multi-digit redis db numbers (eg: "10")

- redis/reply.go
- redis/reply_test.go
This PR adds a `ByteSlices` helper, which is basically the same as `Strings`, except that it's for `[][]byte` instead of for `[]string`. It's nice to have since it doesn't have to do any allocations to convert each element in the array reply from a `[]byte` to a `string`.
> [reply] Add ByteSlices conversion helper

- redis/conn.go
- redis/conn_test.go
The IANA spec for the redis: prefix allows an empty db specifier
(path consisting just of '/') and says to use db 0 in that case.
> Fix #173 (on garyburd/redigo).

- redis/doc.go
- redis/pool_test.go
(fixing upstream, as used in transfer.sh)
> trivial spelling fixes

- redis/conn.go
- redis/go17.go
- redis/pre_go17.go
rediss:// is a valid scheme based on IANA :
https://www.iana.org/assignments/uri-schemes/prov/rediss
We (Heroku) would like to move secure redis connections forward, but
have this chicken and egg problem with some drivers. Drivers for other
languages already support rediss://
> Support rediss:// urls

- redis/conn.go
I'm not sure what you were trying to correct with the original commit - this change reverts a documentation edit that pulled up the function name into the comment itself
> corrected documentation causing build to fail

- redis/pool.go
- redis/pool_test.go
- redis/zpop_example_test.go
This PR adds `IdleCount` method to the `Pool` API as discussed in #251
> Expose current number of idle connections in the pool

- redis/pool.go
As discussed with @garyburd in #252, `ActiveCount` returns the number of all Redis connections (including idle connections) not just the ones currently in use. This PR addresses the issue without breaking the API.
> improve documentation of ActiveCount method

- redis/conn.go
- redis/conn_test.go
- redis/redis.go
- redis/scan.go
- redis/scan_test.go
Add the ability for types to control how they are sent when used as arguments to redis commands.
This is useful for types which don't want to use their Stringer representation when used as an argument to a redis command.
Examples of this is a time.Duration which the user wants to store the number of seconds or a time.Time being stored as int instead of a string.
> Add custom argument representation handling

- redis/test_test.go
Redis 4.0.0 was just released and it changes the log message output.
test_test.go fixed to detect server start based on new message.
> Fix server start detection for Redis 4

- redis/conn.go
- redis/conn_test.go
- redis/doc.go
- redis/redis.go
- Encode result of RedisArg() using same conversion as other arguments. This
change makes []byte return values useful.
- Improve documentation.
> Improve Argument implementation

- redis/pool.go
- redis/pool_test.go
At the moment ActiveCount & IdleCount methods can return the inconsistent state because between calls new operation can be opened or idle connection can be closed because of IdleTimeout. This PR returns consistent stats.
> Method for getting consistent pool statistics added

- redis/pool.go
Missing comma in the comment of Pool to show how to use Dial function.
See: [Issue#305](https://github.com/garyburd/redigo/issues/305)
Thanks:-)
> Add the missing comma in comment(#305).

- .travis.yml
- redis/pool.go
- redis/pool_test.go
The package now requires Go 1.7 or higher.
> Use standard library context package

- README.markdown
Hello,
While the `redisc` package was initially created under the `PuerkitoBio` name, its canonical path is now `mna/redisc`, so I updated it in the readme.
Thanks!
Martin
> update redisc url to canonical one

- README.markdown
This is a new package with support of gomodule/redigo, the old package go-sentinel kept untouched to continue working with garyburd/redigo.
I am not happy with this as this increases entropy but I have not found a better way.
> Change link to Sentinel lib that supports gomodule/redigo

- redis/scan_test.go
When scanning structs, the test suite wasn't properly verifying that
a pointer field should be nil if the redis field doesn't exist.
> Improve tests suite for nil pointer struct scans

- redis/log.go
- redis/pool.go
In log mode, output too many 2018/05/10 15:58:24 redis.Do() -> (<nil>, <nil>).
why c.Do("")?
> delete do empty

- redis/pool.go
- redis/pool_test.go
Add WaitCount and WaitDuration stats to pool stats to enable tracking of the delays introduced by waiting for connections from the pool.
This uses the same properties as database/sql so its familiar to users.
Addresses: #403
> Add wait statistics to pools

- redis/scan.go
- redis/scan_test.go
Add support for scanning into a pointer to a type which supports RedisScan.
Fixes #418
> fix(scan): Support Scan into pointer to RedisScan

- redis/scan.go
- redis/scan_test.go
This commit add code to support scan to struct with ptr fields, e.g.:
```
type S struct {
PtrB *bool
}
```
and flattenStruct from the struct above.
> support scan to ptr and flatten from ptr

- redis/scan.go
- redis/scan_test.go
Given this scenario:
```
type User struct {
CreatedAt Time `redis:"created_at"`
}
type Time struct {
time.Time
}
func (t Time) RedisArg() interface{} {
return t.Unix()
}
```
We'd have the custom `Time.RedisArg` be called when doing `AddFlat`.
Closes https://github.com/gomodule/redigo/issues/444
> addflat: respect RedisArg presence

- redis/redis.go
- redis/reply.go
- redis/reply_test.go
This PR provides support for SLOWLOG GET command results.  A new struct SlowLog has been added which contains the details of the SlowLogs obtained by calling the helper SlowLog
```go
// SlowLog represents a redis SlowLog
// slowLogID - A unique progressive identifier for every slow log entry.
// unixTimeStamp - The unix timestamp at which the logged command was processed.
// executionTime - The amount of time needed for its execution, in microseconds.
// args - The array composing the arguments of the command.
// clientIPAddressAndPort - Client IP address and port (4.0 only).
// clientName - Client name if set via the CLIENT SETNAME command (4.0 only).
type SlowLog struct {
SlowLogID              int64
UnixTimeStamp          int64
ExecutionTime          int64
Args …
```
> Issue#405 Support for SLOWLOG GET command

- redis/conn.go
The go compiler is smart enough to optimize string([]byte) conversion.
```
name       old time/op    new time/op    delta
DoPing-12    29.2µs ± 3%    29.3µs ± 4%   ~     (p=0.730 n=9+9)
name       old alloc/op   new alloc/op   delta
DoPing-12     0.00B          0.00B        ~     (all equal)
name       old allocs/op  new allocs/op  delta
DoPing-12      0.00           0.00        ~     (all equal)
```
> Simplify string reply check

- redis/reply.go
- redis/reply_test.go
> add func Uint64Map Uint64s

- .travis.yml
Remove travis validation against go prior to 1.9.x to allow v3 tagging
to take place: https://github.com/gomodule/redigo/pull/440
> chore: Remove validation against go prior to 1.9.x

- redis/conn.go
- redis/conn_test.go
- fixes #479 
- follows the described in [AUTH](https://redis.io/commands/auth) to connect to a Redis 6.0 instance, or greater, that is using the Redis ACL system.
- adds godoc example for further reference
> Added dialoptions and Url parsing to connect using Redis ACL system

- redis/pool.go
- redis/pool_test.go
I've also stumbled on [this one](https://github.com/gomodule/redigo/pull/426) on a project I've been working on recently. It might lead to pretty nasty scenarios when service under load uses `redigo`.
For some context you can check out [this reddit tread](https://www.reddit.com/r/golang/comments/4ibs68/why_is_the_select_statement_nondeterministic/).
> Handle `ctx` cancellation promptly (when waiting for a vacant connection from the pool)

- redis/scan.go
- redis/scan_test.go
Add Scanner support to ScanSlice.
Previously ScanStruct manually scanned results into structs which didn't use any special handling required by the struct as defined by its RedisScan method.
> feat(ScanSlice): Add Scanner support

- redis/scan.go
Correct grammar in ScanSlice doc string.
> fix: Correct grammar in ScanSlice docs

- .travis.yml
Remove older versions of go from travis config due to the testing dependency testify requiring errors.Is which is only available in go 1.13 and above.
Also switch to master from tip which is the new standard for travis.
> fix(travis): Remove older versions of go

- redis/scan.go
bench result:
```
benchmark                  old ns/op     new ns/op     delta
BenchmarkScanStruct-12     1259          1083          -13.98%
benchmark                  old allocs     new allocs     delta
BenchmarkScanStruct-12     20             17             -15.00%
benchmark                  old bytes     new bytes     delta
BenchmarkScanStruct-12     696           600           -13.79%
```
> use IndexByte improve scan bench

- redis/reply.go
Fixes a super-small typo in the `Ints()` documentation.
> Fix typo in `Ints` documentation

- redis/pool.go
- redis/pool_test.go
This commit releases back the connection in the special
case, so that correct count is always maintained.
Closes #520
> fix: open connection count

- LICENSE
These missing lines was preventing the license_finder gem from detecting
a valid Apache 2.0 license.
> Add End of terms and conditions in LICENSE

- redis/conn.go
- redis/conn_test.go
Add support for configuring a timeout for TLS Handshake call via DialTLSHandshakeTimeout DialOption. If no option is specified then the default timeout is 10 seconds.
Also:
* Add a default connect timeout of 30 seconds matching that of net/http.
Fixes #509
> feat: Add TLS Handshake timeout support

- .github/workflows/golangci-lint.yml
- redis/conn.go
- redis/conn_test.go
- redis/log.go
- redis/pool.go
- redis/pool_test.go
- redis/pubsub.go
- redis/pubsub_example_test.go
- redis/pubsub_test.go
- redis/reply_test.go
- redis/scan.go
- redis/scan_test.go
- redis/script.go
- redis/script_test.go
- redis/test_test.go
- redis/zpop_example_test.go
- redisx/commandinfo.go
- redisx/connmux.go
- redisx/connmux_test.go
- redisx/db_test.go
Enable golangci-lint checking in travis and fix errors identified by it.
> chore: Enable golangci-lint and fix errors

- .clog.toml
Add config for clog which is used for generating release notes from our conventional commits.
For details on the tool see: https://github.com/clog-tool/clog-cli
> chore: Add clog config

- redis/conn.go
and convert DialURL to call DialURLContext()
> Implement DialURLContext(...)

- redis/conn.go
- redis/log.go
- redis/pool.go
- redis/redis.go
- redis/redis_test.go
- redis/script.go
context is mostly used when develop a project
I think the with timeout function can also change to this rule
don't override the readtime
can this be merged and make a new tag?my project need this
by the way,can we fix the tag version number?
> add DoContext and ReceiveContext,use context to control the life

- go.mod
- go.sum
Upgrade to testify 1.7.0
github.com/gomodule/redigo@v1.8.2 › github.com/stretchr/testify@v1.5.1 › gopkg.in/yaml.v2@v2.2.2
> upgrade testify to eliminate security warning

- go.mod
Retract unpublished versions from go tooling.
Also bumps go version to 1.16 as required by retract statement.
Fixes #585
> fix: retract tagged versions

- redis/reply.go
Surface the underlying error when processing results for slice and map helpers so that the user can see the real cause and not a type mismatch error.
Also:
* Formatting changes to improve error case separation.
* Leverage %w in reply errors.
Fixes: #579
> fix: surface underlying error for slice / map helpers

- redis/redis.go
The actual string is "i/o timeout", but it's more clear to test error
identity in the way documented for net.Conn.
Fixes: #600
> fix: correct instructions for detecting DialReadTimeout

- redis/pubsub.go
- redis/pubsub_test.go
Add a wrapper that goes through the standard receiveInternal
processing to match the API of the existing PubSubConn Receive
methods.
Fixes: #592
> feat: add RequestContext to PubSubConn

- redis/reply.go
- redis/reply_test.go
> feat: add Float64Map

- redis/reply.go
Refactor the reply <type>Map helpers to reduce the code duplication in the body of those functions by creating a `mapHelper` along the same lines as the existing `sliceHelper`.
> chore: refactor map helpers to reduce duplication

- .github/workflows/golangci-lint.yml
- redis/reply.go
Hello :wave:
I've noticed that error handling for SlowLogs parser is incorrectly references element 0. This should fix it.
Thanks
> Fixing error message for SlowLog conversion

- redis/conn.go
The `DialContext()` function does not use the new `DoContext()` methods (added in v1.8.6) when configuring auth/clientName/db during connection creation. If the Redis server is unresponsive, this can cause `DialContext()` to run for a very long time (instead of cancelling when the deadline is exceeded). `DoContext` should be used for these cmds.
Repro steps:
1. Make Redis unresponsive: `CLIENT PAUSE 36000000 ALL`
2. Attempt to `DialContext()` with a 1sec timeout
3. Command is unexpectedly blocked for a long time
> fix: respect ctx in cmds run within DialContext

- .github/workflows/golangci-lint.yml
- redis/redis.go
- redis/reply.go
- redis/reply_test.go
- redis/test_test.go
Includes tests similar to how SlowLog was tested.
> Support LATENCY LATEST, LATEST HISTORY command parsing

- .github/workflows/go-test.yml
- .github/workflows/golangci-lint.yml
- redis/conn_test.go
- redis/reply_test.go
Ensure that goroutines started by tests are cleaned up on termination.
Also make TestLatencyHistories compatible with -count=X.
Fixes #641
> fix: test goroutine leaks

- .github/workflows/go-test.yml
- .github/workflows/golangci-lint.yml
- redis/pubsub_test.go
- redis/reply_test.go
Update GitHub actions to use the latest versions and add go mod tidy check.
This bumps go version for tests to 1.20 and 1.21 the currently supported versions.
> ci: update github actions

- redis/test_test.go
This is required for Redis >= 7.x, cf. https://raw.githubusercontent.com/redis/redis/7.0/00-RELEASENOTES:
```
* MODULE and DEBUG commands disabled (protected) by default, for better security (#9920)
```
Without this patch, some unit tests fail:
```
=== RUN   TestLatency
reply_test.go:256:
Error Trace:    /<<PKGBUILDDIR>>/_build/src/github.com/gomodule/redigo/redis/reply_test.go:256
Error:          Received unexpected error:
ERR DEBUG command not allowed. If the enable-debug-command option is set to "local", you can run it from a local connection, otherwise you need to set this option in the configuration file, and then restart the server.
Test:           TestLatency
--- FAIL: TestLatency (0.00s)
=== RUN   TestLatencyHistories
reply_test.go:304:
Error Trace: …
```
> Run the redis test server with enable-debug-command

- redis/reply_test.go
Remove debug check now we run the test server with debug enabled if needed.
> chore: remove debug check

- redis/pool.go
- redis/pool_test.go
- redis/test_test.go
Add TestOnBorrowContext to the Pool struct for checking the health of the idle connection with a given context.
> feat: add TestOnBorrowContext

- .github/workflows/go-test.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/release-build.yml
- .goreleaser.yaml
Add goreleaser to automate the generation of release notes and bump the versions of github actions golang go the latest versions.
> ci: add goreleaser, update action and go versions

- go.mod
Retract v1.8.10 which was tagged incorrectly for a feature release and only available for a few minutes. v1.9.0 is identical.
> chore: retract v1.8.10

- go.mod
Due to our test dependency requiring 1.17 minimum and the 1.16 being well out of support, currently only 1.21 and 1.22 are support releases, bump our required go version to 1.16.
Fixes #665
> fix: bump go version to 1.17

- README.markdown
Document that redigo also supports Valkey
> docs: note support for Valkey

- redis/reply_test.go
Latency tests might fail on busy machines, as the actual latency is longer than expected.
Happens on the Debian build infrastructure:
- https://ci.debian.net/packages/g/golang-github-gomodule-redigo/testing/amd64/58701649/
- https://ci.debian.net/packages/g/golang-github-gomodule-redigo/testing/amd64/58700608/
- https://ci.debian.net/packages/g/golang-github-gomodule-redigo/testing/ppc64el/58700967/
> fix: latency tests

- redis/test_test.go
So that it's possible to run tests with:
```
go test [...] -redis-server valkey-server
```
> fix: honor server-path in test_test.go
