README.markdown
Will enable people check build status from github project-page.
=> Added travis badge

README.markdown
Added the familiar badge that links to godoc documentation of redigo.
=> Added link to godoc.org in Readme

.travis.yml
Added Go 1.6 as another test target in travis.yml
=> Also test with Go 1.6

redis/reply.go
Implemented a helper function for geopos reply.
@garyburd 
Fixes #230
=> Implement geopos reply helper function

redis/reply.go, redis/reply_test.go
- Add Int64s, fixes #246
- Add Float64s, fixes #288
- Move common code for slice functions to a function.
=> Improve slice reply helper functions

redis/reply.go, redis/reply_test.go
=> Support conversion from Redis integers in Ints, Int64s

redis/conn.go, redis/conn_test.go, redis/pool.go, redis/pubsub.go
The change is compatible with old versions of gofmt.
=> Update to gofmt output on tip

redis/conn.go, redis/conn_test.go, redis/log.go, redis/pool.go, redis/pubsub.go, redis/pubsub_test.go, redis/redis.go, redis/redis_test.go
Add methods to set read timeout on call to Do and Receive.
=> Add *WithTimeout methods

redis/conn.go, redis/conn_test.go
=> Handle RESP strings longer than bufio.Reader size

redis/conn.go, redis/conn_test.go, redis/pool_test.go, redis/test_test.go
This pr implements https://github.com/gomodule/redigo/issues/388
=> Add CLIENT SETNAME to dial options

redis/conn_test.go
I am obsessively tidy, So fix spelling mistake. Thanks
=> fix: tiny  spelling mistake;

redis/conn.go, redis/conn_test.go
=> DialURL ignores opaque url

redis/reply.go, redis/reply_test.go
Fix bad tests introduced by Uint64s and Uint64Map work.
Also:
* Fix some doc typos.
=> fix: Uint64s and Uint64Map tests

redis/conn_test.go
Fix some formatting issue when testing on tip.
=> fix: Formatting issues on tip

go.sum, redis/scan.go, redis/scan_test.go
Fix Argument interface processing on struct pointer types which was broken by #428 and not quite corrected by #446.
=> fix: Argument processing on pointers

redis/pool.go
=> Fix Pool.Get to simple code

redis/conn.go, redis/conn_test.go, redis/pool_test.go
=> Add DialContext function

redis/scan.go, redis/scan_test.go
Add support to AddFlat for Anonymous fields which are pointers.
Fixes #487
=> feat(AddFlat): Add support for Anonymous field pointers

redis/pool.go
Remove an check for ctx being nil which is no longer possible.
=> chore: Remove unneeded ctx == nil check

redis/conn.go, redis/conn_test.go
Fix compatibility of DialURL with respect for single component user-info records.
This enables URLs such as redis://mypass@localhost/1 as supported by redis-cli to be used.
=> fix: DialURL compatibility with redis-cli

.github/workflows/go-test.yml
Add a github action which runs go test so we can ensure that tests are passing before we merge changes.
=> chore: add go test action
